// src/app/room/[roomId]/admin/page.tsx
"use client";
import { useEffect } from "react";
// import { AiOutlineCheckCircle, AiOutlineDelete } from "react-icons/ai";
// import { RiQuestionAnswerLine } from "react-icons/ri";

import Header from "@/components/Header";
import Question from "@/components/Question";

export default function AdminRoom({ params }: { params: { roomId: string } }) {
  const { title, questions } = { title: "React", questions: [] };

  const handleDeleteQuestion = (questionId = "") => {
    if (
      window.confirm("voce realmente deseja excluir essa pergunta") &&
      questionId
    ) {
      console.log(`rooms/${params.roomId}/questions/${questionId}`);
    }
  };

  const handleHighlightQuestion = (questionId = "") => {
    if (questionId) {
      console.log(`rooms/${params.roomId}/questions/${questionId}`, {
        isHighlighted: true,
      });
    }
  };

  const handleCheckQuestionAnswer = (questionId = "") => {
    if (questionId) {
      console.log(`rooms/${params.roomId}/questions/${questionId}`, {
        isAnswered: true,
      });
    }
  };

  return (
    <>
      <Header id={params.roomId} admin />
      <main className="max-w-4xl w-full flex flex-col px-8 mx-auto">
        <div className="flex justify-between items-center my-8">
          <h1 className="text-2xl font-bold font-poppins">
            Sala {title}
          </h1>
          {!!questions?.length &&
            <div>
              {questions?.length} perguntas
            </div>
          }
        </div>
        <div className="flex flex-col">
          {questions?.map(({ id, isHighlighted, isAnswered, description }) => {
            return (
              <Question
                key={id}
                author={{ name: "Anonimo", avatar: "", id: `${id}1` }}
                isHighlighted={isHighlighted}
                isAnswered={isAnswered}
                content={description}
              >
                <button
                />
                <button
                />
                <button
                />
              </Question>
            );
          })}
        </div>
      </main>
    </>
  );
}

// src/pages/room/[slug]/admin.vue
<script lang="ts" setup>
const route = useRoute();

import { socket } from "~/lib/socket";

const questions = ref([]);

onMounted(() => {
    socket.emit("join-room", {
        roomId: route.params.slug,
    });

    socket.on("all-questions", (messageValue) => {
        try {
            console.log(messageValue);
            questions.value = messageValue;
        } catch (e) {
            console.error(e);
        }
    });
    socket.on("new-question", (messageValue: string) => {
        try {
            console.log(messageValue);
            questions.value.push(messageValue);
        } catch (e) {
            console.error(e);
        }
    });
});

onBeforeUnmount(() => {
    socket?.disconnect();
});
</script>
<template>
    <div class="bg-gray-50 min-h-screen">
        <HeaderRoom :code="route.params.slug" :isAdmin="true" />
        <main class="max-w-4xl w-full flex flex-col px-8 mx-auto">
            <div class="flex gap-4 items-center my-8">
                <h1 class="text-2xl font-bold font-poppins">Sala</h1>
                <span
                    class="inline-flex items-center gap-x-1.5 py-1.5 px-3 rounded-full text-xs font-medium bg-purple-600 text-white"
                    v-if="questions.length">
                    {{ questions.length }} perguntas
                </span>
            </div>
            <ul>
                <QuestionCard v-for="q in questions" :key="q" :question="q">
                    <div class="flex justify-between items-center gap-2">
                        <span class="text-gray-600">
                            {{ q.like_count }}
                        </span>
                        <button class="text-purple-600">
                            <LucideThumbsUp />
                        </button>
                    </div>
                </QuestionCard>
            </ul>
        </main>
    </div>
</template>
