// src/pages/room/new.vue
<script lang="ts" setup>
const roomTitle = ref("");

async function createNewRoom() {
    const res = await $fetch(`/api/room`, {
        method: "POST",
        body: { title: roomTitle.value.trim() },
    });
    console.log(res);
    if (res?.slug) {
        await navigateTo({ path: `/room/${res?.slug}/admin` });
    }
}
</script>
<template>
    <div class="flex min-h-screen">
        <Aside></Aside>
        <main class="basis-1/2 flex justify-center items-center">
            <div class="max-w-80 w-full flex flex-col">
                <a href="/" class="mx-auto mb-20">
                    <img
                        width="170"
                        src="~/assets/img/logo.svg"
                        alt="Cruel doubt"
                    />
                </a>
                <h2 class="text-center font-poppins font-bold text-2xl mb-4">
                    Criar uma nova sala
                </h2>
                <Input
                    placeholder="Digite o código da sala"
                    v-model="roomTitle"
                />
                <Button @click="createNewRoom">Criar sala</Button>

                <p class="text-gray-400 text-sm mt-4">
                    Quer entrar em uma sala existente?
                    <NuxtLink to="/" class="text-purple-600"
                        >clique aqui</NuxtLink
                    >
                </p>
            </div>
        </main>
    </div>
</template>

// src/app/room/new/page.tsx
"use client";
import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from 'next/navigation'

import logoImg from "@/assets/logo.svg";
import { Aside, Button, Input } from "@/components";

export default function NewRoom() {
  const router = useRouter();
  const [nameRoom, setNameRoom] = useState("");

  const handleCreateRoom = async () => {
    const newRoomName = nameRoom.trim();
    try {
      const res = await fetch("/api/room", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ title: newRoomName }),
      });
      if (!res.ok) {
        throw new Error(`Erro na requisição: ${res.status}`);
      }
      const data = await res.json();
      router.push(`/room/${data.data._id}/admin`);
    } catch (e) {
      console.log(e);
    }
  };

  return (
    <div className="flex min-h-screen">
      <Aside />
      <main className="basis-1/2 flex justify-center items-center">
        <div className="max-w-80 w-full flex flex-col">
          <Link href="/" className="mx-auto mb-20">
            <Image width={170} src={logoImg} alt="Cruel doubt" />
          </Link>
          <h2 className="text-center font-poppins font-bold text-2xl mb-4">
            Criar uma nova sala
          </h2>
          <Input
            value={nameRoom}
            onChange={setNameRoom}
            placeholder="Nome da sala"
          />
          <Button disabled={!nameRoom} onClick={handleCreateRoom} >
            Criar sala
          </Button>

          <p className="text-gray-400 text-sm mt-4">
            Quer entrar em uma sala existente?
            <Link href="/" className="text-purple-600"> clique aqui</Link>
          </p>
        </div>
      </main>
    </div>
  );
}
