// frontend/src/components/Aside.tsx
import { Stack, Image, Text } from "@chakra-ui/react";

import illustrationImg from "../assets/images/illustration.svg";

function Aside() {
  return (
    <Stack
      display={["none", "flex", "flex"]}
      as="aside"
      px="80px"
      justify="center"
      bg="purple.500"
      color="white"
    >
      <Image
        maxW="320px"
        src={illustrationImg}
        alt="Ilustração simbolizando perguntas e respostas"
      />
      <Text fontFamily="poppins" fontWeight="bold" fontSize="4xl">
        Crie salas de Q&amp;A ao-vivo
      </Text>
      <Text fontSize="2xl">Tire as dúvidas da sua audiência em tempo-real</Text>
    </Stack>
  );
}

export default Aside;

// src/components/aside.vue
<template>
    <aside class="bg-purple-600 flex flex-col justify-center text-white px-20 gap-4 basis-1/2">
        <img width="320" src="~/assets/img/illustration.svg" alt="Ilustração simbolizando perguntas e respostas" />
        <p class="font-bold text-4xl font-poppins">
            "Crie salas de Q&A ao-vivo"
        </p>
        <p class="text-2xl">"Tire as dúvidas da sua audiência em tempo-real"</p>
    </aside>
</template>
