// src/components/Button.tsx
import { ReactNode } from "react";

interface IProps {
  children: ReactNode;
  disabled?: boolean;
  onClick: () => Promise<void>;
}

function Button({ disabled = false, children, onClick }: IProps) {
  return (
    <button
      className="bg-violet-500 hover:bg-violet-700 text-white font-bold py-3 w-full rounded disabled:bg-violet-200"
      disabled={disabled}
      onClick={onClick}
    >
      {children}
    </button>
  )
}

export default Button

// src/components/Button.vue
<script lang="ts" setup>
defineProps({
    disabled: {
        type: Boolean,
        default: false,
    },
});
</script>

<template>
    <button
        class="bg-violet-500 hover:bg-violet-700 text-white font-bold py-3 w-full rounded disabled:bg-violet-200"
        :disabled="disabled"
    >
        <slot />
    </button>
</template>
